name    'wuakitv-twemproxy'
version '0.1.1'
source 'UNKNOWN'
author 'wuakitv'
license 'MIT License'
summary 'This modules helps configure Twemproxy.'
description 'This modules compiles from source twemproxy.'
project_page 'https://github.com/wuakitv/puppet-twemproxy'

## Add dependencies, if any:
# dependency 'camptocamp/puppet-monit'
